services:
  db:
    image: postgres
    restart: always
    environment:
      - PGPORT=6012
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bsb@mn
    ports:
      - "6012:5432"
  web:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8001:8001"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
      
volumes:
  static: