services:
  db:
    image: postgres
    restart: always
    environment:
      - PGPORT=6013
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bsb@mn
    ports:
      - "6013:5432"
  web:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8002:8002"
  nginx:
      build: ./nginx
      volumes:
        - static:/static  # Mount the static volume
      ports:
        - "8080:80"  # Use port 8080 for this project's NGINX
      depends_on:
        - web

volumes:
  static: