services:
  db:
    image: postgres
    restart: always
    environment:
      - PGPORT=6013
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bsb@mn
      - TZ=Asia/Ulaanbaatar
    ports:
      - "6013:5432"
  web:
    volumes:
      - static:/static
      - media:/app/main.wheel
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8002:8002"

volumes:
  static:
  media:
