# Generated by Django 5.1 on 2024-08-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Сугалааны код')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тайлбар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн/Зассан огноо')),
            ],
            options={
                'verbose_name': 'Сугалаа',
                'verbose_name_plural': 'Сугалаа',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wheel/')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Хүрд',
                'verbose_name_plural': 'Хүрд',
            },
        ),
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=100, verbose_name='Худалдан авагчийн регистрийн дугаар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн/Зассан огноо')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.lottery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.wheel')),
            ],
            options={
                'verbose_name': 'Сугалааны хариу',
                'verbose_name_plural': 'Сугалааны хариу',
            },
        ),
    ]
