# Generated by Django 5.1 on 2024-08-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='chance',
            field=models.FloatField(default=1.0, help_text='The relative chance of this item being selected.'),
        ),
    ]
