# Generated by Django 5.1 on 2024-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wheel_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='chance',
            field=models.FloatField(default=1.0, help_text='Chance of taarah magadlal'),
        ),
    ]
