# Generated by Django 5.1 on 2024-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wheel_quantity_alter_wheel_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='wheel_slice_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
