# Generated by Django 5.1 on 2024-08-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wheel_wheel_slice_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='wheel_text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
