# Generated by Django 5.1 on 2024-08-21 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wheel_wheel_text_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotteryresult',
            old_name='register_no',
            new_name='phone_no',
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 41, 11, 450528), verbose_name='Үүссэн огноо'),
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 9, 41, 11, 450543), verbose_name='Шинэчилсэн/Зассан огноо'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='chance',
            field=models.FloatField(default=1.0, help_text='Зөвхөн тоо хийх | % бичиж болохгүй', verbose_name='Таарах магадлал'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='image',
            field=models.ImageField(upload_to='wheel/', verbose_name='Барааны зураг'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Хүрдэнд харагдах эсэх'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Үлдэгдэл'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Барааны нэр'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='wheel_slice_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Хүрдний хэрчмийн өнгө'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='wheel_text_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Хүрдний хэрчмийн текст өнгө'),
        ),
    ]
