# Generated by Django 5.0.4 on 2024-08-21 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_register_no_lotteryresult_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryresult',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 21, 48, 18, 699128), verbose_name='Үүссэн огноо'),
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 21, 48, 18, 699128), verbose_name='Шинэчилсэн/Зассан огноо'),
        ),
    ]
