# Generated by Django 5.0.4 on 2024-10-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lotteryresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryresult',
            name='created_at',
            field=models.DateTimeField(verbose_name='Үүссэн огноо'),
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн/Зассан огноо'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Шагналгүй хүрд эсэх'),
        ),
    ]
