# Generated by Django 5.0.4 on 2024-10-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_lotteryresult_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='wheel',
            name='branch',
            field=models.IntegerField(choices=[('--------', 0), ('Гэрийн мебель', 1), ('Оффис мебель', 2), ('Орон нутаг', 3)], default=0),
        ),
        migrations.AddField(
            model_name='wheel',
            name='is_prize',
            field=models.BooleanField(default=True, verbose_name='Шагналтай хүрд эсэх'),
        ),
    ]
